### ISSUE TITLE
Unable to generate ROI.

### ISSUE THREAD

**Issue by amartekdi** [Sunbird-Saral/Saral-Layout-Generator#13]
While trying to add input box by clicking on button "Add input box".Pop up box of  configuration to select box type , order ,name is not showing in some scenario . hence it  configure  wrong ROI and disable the generate ROI button.

**Comment by sanjay-v46** [comment]
We have taken the reported bug for resolution.

**Comment by sanjay-v46** [comment]
@amartekdi The fix is done for the reported issue. PR #14

**Comment by amartekdi** [comment]
@sanjay-v46 Still facing the issue.Please try the below scenario.
1.Click on "Add input box".
2.Enter the name of the field.
3.Select any one Field type & enter length for it.
4.Now remove length and click on apply.
